### ISSUE TITLE
Missing features to switch from waybar

### ISSUE THREAD

**Issue by clotodex** [MalpenZibo/ashell#128]
I find this project super interesting and have long been looking for an opinionated out-of-the-box bar. Love pretty much everything about it!

There are however a few things missing so I would switch from waybar and are creating this issue as a tracking issue for myself as well as for feedback what is compatible with this repo, and what would not get merged.

A live comparison - as you can see, not far apart.

![Image](https://github.com/user-attachments/assets/8963a200-7fde-418e-bd86-30653beab87b)

The missing features for me:

Windows/Workspaces:
- Multimonitor: would like the active workspace on the other monitor to be a different color
- Alerted windows support (as you can see with the "!" and red color)

Broken modules:
- Network - I use raw iwd (could be implemented with iwdrs)
- Airplane mode

New Modules:
- Standalone: Connected bluetooth device
- Standalone: Wifi (strength / status)
- SwayNC for notification management

Custom Modules:
- IconModule - Icon that launches a specified command (e.g. qr code scanner, ..) - similar to launcher
- IconDynamicModule - IconModule, but Icon can switch based on command output that could be polled - super flexible to just add any type of extra info

Style (preference)
- different backgrounds of modules (especially the workspaces I would like to be way less intrusive)
- collapse behind icon (e.g. system info) - could be a collapsed icon, if i wanna see it i can hover on the icon
- MediaPlayer - spotify is shown after browser - I would like to specify preference or switch it with click (could be separate issue)
- Volume indication or percent directly in module
- I am using "hover for more info" a lot (e.g. calendar for date, wifi network for wifi, ...)

**Comment by MalpenZibo** [comment]
Thanks for the feedback. In the next few days I should return from my holiday.

I will check what could be done!

**Comment by clotodex** [comment]
working on iwd in #129 (the state of iwd dbus in rust was virtually non-existant, and async traits with impl Stream are a b***). Feel free to have a look, will continue in the upcoming week.

**Comment by clotodex** [comment]
Also implemented minimal custom module support in #131

**Comment by MalpenZibo** [comment]
Ok, I'm back!

Let's start:
- IconModule and IconDynamicModule: I have already thought about it. It should be an easy change and could replace the AppLauncher and the Clipboard module.
- File system usage (and other info like network download/upload speed): I opened a PR that improves the SystemInfo module to support these use cases
- MediaPlayer: I should improve this module, the reality is that I never use that module 😅. I could find a way to re-order the list of players (maybe letting the user specify a list of "favorite" players).

- Volume indication or percent directly in module: Do you mean that the icon on the bar should have the percent always visible? Right now, the icon changes based on the volume (like the wifi icon) but doesn't show the exact volume level. I can add an option to also display the percent value. 
- hide until threshold: I don't understand 😅 . Do you mean to hide the entire bar after a while without interaction?
- Alerted windows support: I don't understand. Should I indicate if a workspace has an alert window? I don't know where to get this info

- Network iwd: I'm not using iwd, so I cannot maintain the codebase (I don't have too much time to dedicate to this project, so I'm trying to maintain the codebase as maintainable as I can). I see that you have already opened a PR. Thank you so much. Probably I cannot test it right now, but if you already use that code on your system, I can merge that module (maybe as an experimental one)
- Connected bluetooth device (name): I can add an option to show the connected device on the status bar. I would like to maintain this information in the systemModule (so this information will go near the wifi and speaker icon), but I can understand that someone may prefer this information somewhere else. Also, in case of multiple devices, which one should I display?
- SwayNC for notification management: I planned to implement something to play with the notification
- different backgrounds of modules: I need to think about it. I'm not a big fan of this idea right now.
- collapse behind icon and hover for more info: As a design choice, I prefer to open the menu with a click. Also, right now, the iced toolkit doesn't have animations, so every "expand" functionality on mouse hover will have a not-so-pleasant effect. I will think about it

**Comment by clotodex** [comment]
Welcome back! Thank you for your feedback! I came to love this little bar - it just works :D
In terms of workload, I am happy to contribute, but would need a bit of guidance in your coding style or how to architect certain changes - all feedback or thoughts here are appreciated - so this project does not end up to "spaghetti-codey". Worst case I can also fork away, but I would rather try to keep it maintained instead :)

I already built my complete dealbreakers (iwd and custom modules), but would love to flesh the rest out.
Alrighty here my direct responses:

- IconModule and IconDynamicModule: I have already thought about it. It should be an easy change and could replace the AppLauncher and the Clipboard module. - Already done in #131 - check it out if this fits what you had in mind

- File system usage ✅ 

- MediaPlayer: I will check it out when I get to it, I also want the title truncation here etc :D so might just create a PR

- Volume indication or percent directly in module: yes exactly. My audio can go above 100%, and I want to see it a bit more finegrained than 3 states. Probably implementing more states and an "overdrive" state could be fine. Also the percent could be a hover tooltip - dont know how hard that is though

- hide until threshold: hahha sorry could have been more specific. I mean this: Imagine the hard drive space module. I dont care about seeing it, until it goes above 70%. So hide the module until a threshold. This should be relatively simple to implement, as soon as #127 is merged

- Alerted windows support: yes exactly! I did a bit of googling and seems like this is an "urgent" event that gets sent by hyprland and is supported in hyprland-rs

- Network iwd: Please check out #129, I am happy to continue developing and marking it as experimental. I do need your feedback though on my code-choices, if this works for you. If you think the API or way we integrate different backends should be different, please let me know.

- Connected bluetooth device (name): yeah exactly. in terms of what to display, we can start with most recent. Otherwise I like to see my earbuds there mostly, dont know how waybar does it. But for now simply having it is nice, and then we can see how to configure or optimize i guess.

- SwayNC: for me this is all about rendering. I wanna see the amount of notifications, that there are new ones etc. So it would need to be: 1) an icon that changes based on state 2) probably an alert dot (but could live without it) 3) number of notifications 4) on click open swaync (just execute command). If you think something more general this is also fine and I might contribute a hardcoded custom module some other time.

- different backgrounds of modules: fair. For me this is only the workspaces. But dont wanna bloat configuration either.

- collapse behind icon: click is fine, animations i dont need - would limit to non-interactive modules i guess (or we close it on a timer ...). Also thinking

**Comment by MalpenZibo** [comment]
Perfect! Sorry but in this period I don't have much time. But I was able to setup another PC to make some test on different thing.

I will prioritize you PR as soon as I can.

Thanks again for your contribution

**Comment by clotodex** [comment]
Extra info on hover should be relatively straight forward in the future: https://docs.rs/iced/latest/iced/widget/fn.hover.html, https://giesch.dev/iced-hoverable/

**Comment by rahatarmanahmed** [comment]
FWIW I was looking for iwd support but ended up installing NetworkManager and used iwd as a backend (mostly b/c i liked nm-connection-editor better than iwgtk). That made ashell start showing the wifi buttons, although scanning doesn't seem to work. Not sure if the iwd PR would address that.

**Comment by clotodex** [comment]
My state with iwd is quite nice tbh. Everything works for me - the only two things i am struggling with still:
- entering passwords (almost done, but since iwd is reactive and not imperative here (i.e. it asks for a password on dbus) this was more complicated - i have a version locally though where i am close)
- automatically updating the current network strength - technically implemented but does not work - no idea why yet
- fancy things like updates on ipv6 resolution etc i will defer to the future but are also possible (network manager needs to get it from somewhere anyways)

I also checked out waybars implementation and they seem to just listen to file descriptors to check bandwidth. What iwd does not cover is LAN connections (i think), so that would also be open for the future.

**Comment by clotodex** [comment]
I finally figured out what is annoying me about the multi-monitor setup.

![Image](https://github.com/user-attachments/assets/9db2e5af-9904-41ae-8306-f5182ac80c45) vs my old waybar: 

![Image](https://github.com/user-attachments/assets/6648505f-7932-4ec8-9fb9-bb80d747f679)

On ashell it colors the workspaces based on the visit HISTORY (so I know what i *had* open on each monitor)
My waybar shows me what I HAVE open - it is immediately clear to me that 4 is the globally selected workspace and 6 is open on the other monitor. Will tackle this later - but is this better or just my own preference? wdyt?

**Comment by MalpenZibo** [comment]
Hum... I don't know if I get the difference.

I saw that in your waybar config, only the "active" workspaces are colored, and the focused one is larger.

In ashell every workspace is colored based on the corresponding monitor, and the focused one is larger (there are also situations in which the workspace has only a colored border that indicates empty workspaces)

If I understand, the problem is that ashel adds colors also to "inactive" workspaces?

**Comment by clotodex** [comment]
Exactly, not necessarily a "problem" but rather a preference of mine - since i often send windows between the monitors and wanna know what is open on the other one. So not sure if ashell needs to change or just a config option or my own personal preference alone :D

**Comment by romanstingler** [comment]
@clotodex could you check your list and for each open feature/bug create a separate ticket where we can discuss everything separately. 
this would be way easier than reading through outdated points.

**Comment by clotodex** [comment]
Haha yes i can
Since i am not using Waybar for a while now i assume that the important stuff was solved

I think alerted windows are still open but would track this in the general wayland support issue

A standalone bluetooth module could be cool if hooked into the same service - but could easily be a custom module for now
@romanstingler is there some kind of issue tracking potential bluetooth module improvments?

Potentially there are some mediaplayer issues (tracked somewhere) but need to write up a proper issue for this

Thanks for your work @romanstingler

**Comment by romanstingler** [comment]
Basically I am working now on this 
https://github.com/MalpenZibo/ashell/issues/399

very unspecific i know :) 

but basically if you create any issues for mplayer or bt I will just add them to my list 
and I will also add a settings split.

yesterday I saw 
https://github.com/MalpenZibo/ashell/issues/326

and I think that I want to see if I can make some small improvements for now. 
maybe tooltips on mouse over hover like 

- show the audio device
- show BT device
- show network ssid
- show battery remaining 
- show device name and battery remaining on peripheral battery
- right click on audio to open pavucontrol directly
- right click on BT and Network to open the app to manage that

I don't know how much time I will have during the week, but hopefully this will help some guys.
And hopefully you agree on these for now, until we discuss how to split them and maybe let users have a list of functions and a list of mouse thingies like scroll up, hover/tooltip, left click, right click, where they can map function to mouse action.
But that will be in the future.

I think that all the PRs that i have open are covering at least the biggest issues that are open and I am aware of.
And also add a few small things that make life easier. 

as soon as @MalpenZibo has more time for discussions we can make bigger refactors
 (I don't know if he wants some features like custom text and use placeholders, or how this should be structured in the config,...). 


Regarding Mplayer
there is 
- https://github.com/MalpenZibo/ashell/pull/319
and 
I had a look at the following but couldn't reproduce the issue
- https://github.com/MalpenZibo/ashell/issues/267

As I said if you see anything just open an issue.

**Comment by anuramat** [comment]
would a window minimap like https://github.com/calico32/waybar-niri-windows be possible?

**Comment by clotodex** [comment]
That is quite extensive in my eyes (expanding the IPC already implemented and then offering a new module for rendering workspace details. Potentially a (distant cousing) of #495 . Feel free to open a separate issue with your usecase though :)

**Comment by romanstingler** [comment]
@clotodex it is pretty hard to step through what is still missing on your side. 
can you create atomic issues for the open points and maybe there are already some open. 
And then we can close this one/

**Comment by clotodex** [comment]
all here :) thank you.
A few details we can take as ideas for other features but nothing important enough to keep tracking.
Closing 🎉
